from enum import StrEnum


class AccessClass(StrEnum):
    PUBLIC_OFFICIAL = "PUBLIC_OFFICIAL"
    PUBLIC_COMPANY = "PUBLIC_COMPANY"
    PUBLIC_REGULATORY = "PUBLIC_REGULATORY"
    LICENSED_OPTIONAL = "LICENSED_OPTIONAL"
    ACCOUNT_OR_FEE_ACCESSIBLE = "ACCOUNT_OR_FEE_ACCESSIBLE"
    SYNTHETIC_TEST = "SYNTHETIC_TEST"
    INTERNAL_OR_CONFIDENTIAL = "INTERNAL_OR_CONFIDENTIAL"


class VersionType(StrEnum):
    PUBLIC_TARGET_OR_GUIDANCE = "PUBLIC_TARGET_OR_GUIDANCE"
    ANALYST_PLAN = "ANALYST_PLAN"
    ANALYST_FORECAST = "ANALYST_FORECAST"
    SCENARIO = "SCENARIO"
    PUBLIC_ACTUAL = "PUBLIC_ACTUAL"
    EXTERNAL_ESTIMATE = "EXTERNAL_ESTIMATE"


class PublicationStatus(StrEnum):
    PRELIMINARY = "PRELIMINARY"
    FILED = "FILED"
    REVISED = "REVISED"
    RESTATED = "RESTATED"


class ScenarioPurpose(StrEnum):
    STATUS_QUO = "STATUS_QUO"
    OPTION_CASE = "OPTION_CASE"
    ANALYST_BASE = "ANALYST_BASE"
    EVIDENCE_DOWNSIDE = "EVIDENCE_DOWNSIDE"
    REVERSE_STRESS = "REVERSE_STRESS"


class Perspective(StrEnum):
    CORPORATE_VALUE = "CORPORATE_VALUE"
    PERFORMANCE_MANAGEMENT = "PERFORMANCE_MANAGEMENT"
    ISSUER_CAPACITY = "ISSUER_CAPACITY"
    INSTRUMENT_RECOVERY = "INSTRUMENT_RECOVERY"


class ModuleId(StrEnum):
    M1 = "M1"
    M2 = "M2"
    M3 = "M3"
    O1 = "O1"


class GateStatus(StrEnum):
    NOT_EVALUATED = "NOT_EVALUATED"
    PASS = "PASS"
    FAIL = "FAIL"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    WITHHELD = "WITHHELD"


class ClaimTag(StrEnum):
    FACT = "F"
    DERIVED = "D"
    ASSUMPTION = "A"
    INFERENCE = "I"
    RECOMMENDATION = "R"
    MEASURED = "M"


class KnowledgeState(StrEnum):
    KNOWN = "KNOWN"
    UNKNOWN = "UNKNOWN"
    NM = "NM"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    NOT_TESTABLE_FROM_PUBLIC_DATA = "NOT_TESTABLE_FROM_PUBLIC_DATA"
    WITHHELD = "WITHHELD"


class AccountingScope(StrEnum):
    CONSOLIDATED = "CONSOLIDATED"
    STANDALONE = "STANDALONE"

